### ISSUE TITLE
panic in rdp_proto::nego::parse_negotiation_request

### ISSUE THREAD

**Issue by ekse** [Devolutions/devolutions-jet#17]
This fuzzing case triggers a panic when calling `consume` on a slice.

fuzz case: https://drive.google.com/file/d/1DtCGePWZlBaW4WRo1Lpc2duNqrc_rl72

Note: The fuzzers are currently on the `fuzzers` branch.

Crash output:

```
cargo +nightly fuzz run fuzz_nego

thread '<unnamed>' panicked at 'slice index starts at 19 but ends at 18', src/libcore/slice/mod.rs:2561:5

14: std::io::impls::<impl std::io::BufRead for &[u8]>::consume
             at /rustc/0b680cfce544ff9a59d720020e397c4bf3346650/src/libstd/io/impls.rs:263
  15: rdp_proto::nego::parse_negotiation_request
             at ./src/nego.rs:187
  16: rust_fuzzer_test_input
             at fuzz_targets/fuzz_nego.rs:15
```

Crashing code in nego.rs:

```rust
let nego_data = if let Some((nego_data, read_len)) = read_nego_data(slice) {
        slice.consume(read_len);
```

**Comment by ekse** [comment]
The crash was fixed in https://github.com/Devolutions/IronRDP/pull/4/.
